services:
  web:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
    env_file:
      - ./.env
    environment:
      - NGINX_HOST="${NGINX_HOST:-localhost}"
      - NGINX_PORT=80
    volumes:
      - ./src:/usr/share/nginx/html
